# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:

    # Alfresco Repository, using "useDynamicShardRegistration" for SOLR Shard discovery
    # Messaging Subsystem has been disabled, as it's not used in Alfresco Community
    alfresco:
        image: alfresco/alfresco-content-repository-community:${ALFRESCO_CE_TAG}
        mem_limit: 1500m
        environment:
            JAVA_OPTS : "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.useDynamicShardRegistration=true
                -Dsolr.port.ssl=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=localhost
                -Ddeployment.method=DOCKER_COMPOSE
                -Dcsrf.filter.enabled=false
                -Dalfresco.restApi.basicAuthScheme=true
                -Dmessaging.subsystem.autoStart=false
                -Dalfresco.restApi.basicAuthScheme=true
                -Xms1g -Xmx1g
                "

    # Shard 1 (DB_ID routing)
    solr6shard1:
        build:
          context: ./search
          args:
            SEARCH_TAG: ${SEARCH_CE_TAG}
            SOLR_HOSTNAME: solr6shard1
            NUM_SHARDS: "2"
            SHARD_ID: "0"
        mem_limit: 1500m
        environment:
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "8080"
            SOLR_SOLR_HOST: "solr6master"
            SOLR_SOLR_PORT: "8983"
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms1g -Xmx1g"

    # Shard 2 (DB_ID routing)
    solr6shard2:
        build:
          context: ./search
          args:
            SEARCH_TAG: ${SEARCH_CE_TAG}
            SOLR_HOSTNAME: solr6shard2
            NUM_SHARDS: "2"
            SHARD_ID: "1"
        mem_limit: 1500m
        environment:
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "8080"
            SOLR_SOLR_HOST: "solr6slave"
            SOLR_SOLR_PORT: "8983"
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms1g -Xmx1g"

    share:
        image: alfresco/alfresco-share:${SHARE_TAG}
        mem_limit: 1g
        environment:
            - REPO_HOST=alfresco
            - REPO_PORT=8080
            - "CATALINA_OPTS= -Xms500m -Xmx500m"

    postgres:
        image: postgres:${POSTGRES_TAG}
        mem_limit: 1500m
        environment:
            POSTGRES_PASSWORD: alfresco
            POSTGRES_USER: alfresco
            POSTGRES_DB: alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5432:5432

    # HTTP proxy to provide HTTP Default port access to services
    # SOLR API and SOLR Web Console are protected to avoid unauthenticated access
    proxy:
        image: nginx:stable-alpine
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./config/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd
        ports:
            - 80:80
